version: "3.9"
services:
  server:
    image: tetrade/inspection:0.0.4.6
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/inspection-service-db
      - aws.s3.host=http://minio:9000/
    ports:
      - "8080:8080"
    restart: on-failure


  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "inspection-service-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"


  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'VijXp8374JgAMUaER8oy'
      MINIO_ROOT_PASSWORD: 'F5Fp7IOb5TEEf7GV4teUAJxOj11H781fP2h2i2cQ'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_REGION: 'ru-msk'
    command: minio server /data

  client:
    image: alina2002alina/front:0.0.4.5
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8082:80"
    volumes:

        - ./nginx/:/etc/nginx/conf.d/
        - /etc/letsencrypt/:/etc/letsencrypt/

    depends_on:
      - server
    links:
      - server
    restart: always

#  webserver:
#      image: nginx:latest
#      ports:
#        - 80:80
#        - 443:443
#      restart: always
#      volumes:
#        - ./nginx/:/etc/nginx/conf.d/:ro
#        - ./certbot/www:/var/www/certbot/:ro
#        - ./certbot/conf/:/etc/nginx/ssl/:ro
#      depends_on:
#        - certbot
#  certbot:
#      image: certbot/certbot:latest
#      volumes:
#        - ./certbot/www/:/var/www/certbot/:rw
#        - ./certbot/conf/:/etc/letsencrypt/:rw
